# Generated by Django 5.2.4 on 2025-08-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='contract_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='experience_level',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='languages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='nice_to_have',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='requirements',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='salary_range',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='technologies',
            field=models.JSONField(default=list),
        ),
    ]
